[package]
name = "openssl-src"
version = "110.0.6+1.1.0h"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/openssl-src-rs"
description = """
Source of OpenSSL and logic to build it.
"""

[workspace]
members = ['testcrate']

[dependencies]
cc = "1.0"
